### ISSUE TITLE
Some technical details about creating x11docker-deepin image from scratch. 

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#24]
I still have some questions  on creating x11docker-deepin image from scratch as shown below:

1. I noticed the following message during the building process:

```
Try updating from "http://cdn.packages.deepin.com/deepin/tree/lastore" to "/var/lib/lastore/tree"

3506 metadata, 2199 content objects fetched; 8991 KiB transferred in 488 seconds
E: gzip: invalid header
E: GenerateCategory failed EOF
```

Compared to the other steps, the above step has very low network speed. And furthermore, some errors have occurred as shown above. 

Any hints for this problem?

2. I still can't figure out the mechanism of [the Dockerfile used by bestwu](https://github.com/bestwu/docker-deepin/blob/master/amd64/Dockerfile), say, the following parts:

```
COPY stable /usr/share/debootstrap/scripts/lion
COPY deepin-archive-keyring.gpg /usr/share/keyrings/deepin-archive-keyring.gpg
COPY deepin-pools-keyring.gpg /root/deepin-pools-keyring.gpg
RUN apt-get update && apt-get install -y debootstrap && \
    debootstrap --variant=minbase --no-check-gpg --arch=amd64 lion rootfs http://packages.deepin.com/deepin/ && \
    cp /usr/share/keyrings/deepin-archive-keyring.gpg rootfs/etc/apt/trusted.gpg.d/ && \
    cp /root/deepin-pools-keyring.gpg rootfs/etc/apt/trusted.gpg.d/ && \
    chroot ./rootfs apt-get autoclean && \
    chroot ./rootfs apt-get clean
```

Why is rootfs used here to complete the work of debootstrap? Why must the apt-get operations be done with chroot? Why  should the file stable have the following content?:

```
mirror_style release
download_style apt
finddebs_style from-indices
variants - buildd fakechroot minbase
keyring /usr/share/keyrings/deepin-archive-keyring.gpg

# include common settings
if [ -e "$DEBOOTSTRAP_DIR/scripts/debian-common" ]; then
 . "$DEBOOTSTRAP_DIR/scripts/debian-common"
elif [ -e /debootstrap/debian-common ]; then
 . /debootstrap/debian-common
else
 error 1 NOCOMMON "File not found: debian-common"
fi
```

Regards,
HY

**Comment by mviereck** [comment]
So far I did not try to understand the details of the bestwu/deepin Dockerfile. In fact, I am still confused on some details. Most important is to understand the handling of the keyring files and to provide vaild keyring files.
Some basic conclusions:

> Why is rootfs used here to complete the work of debootstrap? 

`rootfs` is the folder where debootstrag stored the files. Did you mean `chroot`?

The idea is: 
 - Use the existing debian image to download a deepin system with debootstrap.
 - Provide some authentication files formerly introduced with `COPY`
 - Make the image smaller with deleting files using `chroot`.
 - Switch from debian to the deepin system.

I'd say the `chroot` commands are not needed at all.

> Why should the file stable have the following content?

Those are instructions for `debootstrap` how to download deepin. I am not familiar with debootstrap, so I can't tell the details.
Important to check is the authentication file:
```
keyring /usr/share/keyrings/deepin-archive-keyring.gpg
```

----------------
>    I noticed the following message during the building process:

I don't know. Maybe ask bestwu if he has an idea.

----

Note that the entire debian system is dropped and only the former content of `/rootfs` remains since this step:
```
FROM scratch
COPY --from=0 /rootfs /
```

**Comment by hongyi-zhao** [comment]
> I'd say the `chroot` commands are not needed at all.

This is what I want to know. Why?

**Comment by mviereck** [comment]
```
    chroot ./rootfs apt-get autoclean && \
    chroot ./rootfs apt-get clean && \
    chroot ./rootfs rm -rvf /usr/share/icons/Adwaita && \
    chroot ./rootfs find /var/lib/apt/lists -type f -delete && \
    chroot ./rootfs find /var/cache -type f -delete && \
    chroot ./rootfs find /var/log -type f -delete && \
    chroot ./rootfs find /usr/share/doc -type f -delete && \
    chroot ./rootfs find /usr/share/man -type f -delete && \
    chroot ./rootfs find /usr/share/locale -type f -delete
```
The chroot commands delete several files to make the image smaller. That's the only purpose.
If deleting the files after `COPY --from=0 /rootfs /` the image would keep its size.
This is due to the layer concept of docker. New instructions create a new layer above previous layers. 
For example:
```
RUN echo "xyz" > /file
RUN rm /file
```
The first RUN creates a layer where a file '/file` exists.
The second RUN creates a layer where this file does not exist.
But both layers are stored. So the file still exists in the image, but is not visible in container.
The file would only disappear entirely with:
```
RUN echo "xyz" > /file && \
    rm /file
```

**Comment by hongyi-zhao** [comment]
Seems similar to the concept of the atomicity in database, i.e., the deleting operation must happen in the same layer and after the creating operation. In this way, the whole process of them forms a transaction.

Anyway, I've deleted all the chroot commands used by [*bestwu*](https://github.com/bestwu/docker-deepin/blob/master/amd64/Dockerfile) in my customized Dockerfile.
